# Generated by Django 5.0.3 on 2024-06-04 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passanger_name', models.CharField(max_length=100)),
                ('passanger_email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.flightlocation')),
            ],
        ),
    ]
